import { Inter } from "next/font/google";
import "./globals.css";
import TransitionProvider from "@/components/transitionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Abdur Rehman Malik",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="min-h-screen bg-gradient-to-b from-[#b3d4fc] via-[#d6c8e5] to-[#f3c6c6]"
      >
        <TransitionProvider>{children}</TransitionProvider>
      </body>
    </html>
  );
}
